runtime: nodejs18
env: standard

instance_class: F2

env_variables:
  NODE_ENV: "production"
  PORT: "8080"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65

handlers:
- url: /.*
  script: auto
  secure: always