# shopify.app.toml
client_id = "TU_CLIENT_ID_AQUI"
name = "POS FEL WhatsApp"
handle = "pos-fel-whatsapp"
application_url = "https://tu-app.googlecloud.com"
embedded = false

[build]
dev_store_url = "TU_TIENDA.myshopify.com"

[access_scopes]
scopes = "read_products,write_products,read_customers,write_customers,read_orders,write_orders,read_inventory,write_inventory"

[auth]
redirect_urls = [
  "https://tu-app.googlecloud.com/auth/callback",
  "https://tu-app.googlecloud.com/auth/shopify/callback",
  "https://tu-app.googlecloud.com/api/auth/callback",
  "http://localhost:3000/auth/callback",
  "http://localhost:3000/auth/shopify/callback",
  "http://localhost:3000/api/auth/callback"
]

[webhooks]
api_version = "2025-07"

[pos]
embedded = false

[network]
automatically_update_urls_on_dev = true